name: CLC
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
baseurl: /
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      version: "vx"
      githubbranch: "release-x"
      docsbranch: "master"
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty
